name: Rust CI

on:
 workflow_call:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-

      - name: Install Rust (nightly with components)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly  
          override: true
          components: clippy, rustfmt

      - name: Check code format
        run: |
          cargo fmt --all -- --check

      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Build and test code
        run: |
          cargo build --verbose
          cargo test --verbose